#-------------------------------
# General Site Settings
#
title: Angelo Cordon | Web Designer & Developer
description: I love beautiful brands well thought-out products. I co-founded A Vivid Visual and Filipinos Forward. Every now and then, I try to blog about my entrepreneurship escapades.
email: angelo@avividvisual.com

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: I love beautiful brands well thought-out products. I co-founded A Vivid Visual and Filipinos Forward. Every now and then, I try to blog about my entrepreneurship escapades.
  # rel-author:
  # rel-publisher:

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# Social

social:
- {link: LinkedIn, icon: linkedin, url: 'htp://www.linkedin.com/in/angelocordon'}
- {link: Github, icon: github-alt, url: 'http://www.github.com/angelocordon'}
- {link: Dribbble, icon: dribbble, url: 'http://www.dribbble.com/angelocordon'}
- {link: Behance, icon: behance, url: 'http://www.behance.net/angelocordon'}

#-------------------------------
# Past-Projects

projects:
- {name: 'OppSites', desc: 'Through several design sprints, built and worked on numerous key features using Ruby on Rails and Angular with short turn-arounds. Co-managed an outsourced team overseas to help us with bigger features and goals.', url: 'http://www.oppsites.com' }
- {name: 'Shiploop', desc: 'Designed a mobile application to help customers schedule their package deliveries.', url: 'https://itunes.apple.com/us/app/shiploop/id981775905?mt=8' }
- {name: 'Bevvy', desc: 'A web platform for drinkers by drinkers. Designed newsletter templates and many key pages and modules of the site.', url: 'http://www.bevvy.co' }
- {name: 'Sovereign Gaming League', desc: 'Designed and developed an e-sports web platform. Tech used: Ruby on Rails and AWS.' }
- {name: 'The Great Baby Romp', desc: 'Designed and developed a custom Squarespace template for annual San Francisco based parenting conference.' }
- {name: 'Ask a Nanny', desc: 'Created a responsive, custom Squarespace template for child development blogger, Stef Tousignant.', url: 'http://www.askananny.com' }
- {name: 'Life Well Organized', desc: 'Designed and developed. Built using PHP to create a modularized architecture to plug and play various body content with footer and navigation elements. Used Javascript libraries to create a smooth user experience.', url: 'http://www.lifewellorganized.com'}
