#-------------------------------
# General Site Settings
#
title: Angelo Cordon | Web Designer & Developer
description: I love beautiful brands well thought-out products. I co-founded A Vivid Visual and Filipinos Forward. Every now and then, I try to blog about my entrepreneurship escapades.
email: angelo@avividvisual.com

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: I love beautiful brands well thought-out products. I co-founded A Vivid Visual and Filipinos Forward. Every now and then, I try to blog about my entrepreneurship escapades.
  # rel-author:
  # rel-publisher:

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# Social

social:
- {link: LinkedIn, icon: linkedin, url: 'htp://www.linkedin.com/in/angelocordon'}
- {link: Behance, icon: behance, url: 'http://www.behance.net/angelocordon'}
- {link: Dribbble, icon: dribbble, url: 'http://www.dribbble.com/angelocordon'}
- {link: Github, icon: github-alt, url: 'http://www.github.com/angelocordon'}

#-------------------------------
# Past-Projects

projects:
- {name: 'A Vivid Visual', desc: "AVV's website is built with Jekyll and SASS, and hosted on Github.",url: 'avividvisual', github: 'avividvisual/avividvisual.github.io' }
- {name: 'Sovereign Gaming League', desc: "Built a web-application using Ruby on Rails, SASS, Heroku and AWS." }
- {name: 'The Great Baby Romp', desc: "Customized and branded a template for use with the Squarespace platform. Used Squarespace's version of Liquid, LESS for styling and Bootstrap." }
- {name: 'Ask a Nanny', desc: " Created a custom Squarespace template that copied the original design from an iWeb blog. Also implemented a responsive layout using media queries and javascript. Tools used: Git, LESS, Bootstrap, Vanilla JS", url: 'askananny'}
- {name: 'Life Well Organized', desc: "Designed and developed. Built using PHP to create a modularized architecture to plug and play various body content with footer and navigation elements. Used Javascript libraries to create a smooth user experience.", url: 'lifewellorganized'}
